- name: MYSQL Server installation
  hosts: all
  become: true
  tasks:
    - name: setup prompt
      ansible.builtin.shell: set-prompt mysql

    - name: Installing the mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: Start mysql Service
      ansible.builtin.systemd_service:
        name: mysqld
        state: restarted
        enabled: true

    - name: change the default root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1